  
sudo: required
services:
  - docker

before_install:
  - docker build -t dockerrandy729/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true dockerrandy729/docker-react npm run test
deploy:
  edge: true 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Norman-app"
  env: "Norman-env"
  bucket_name: "elasticbeanstalk-us-east-1-967195537723"
  bucket_path: "Norman-app"
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
